### ISSUE TITLE
Xen 4.12.3 + backports compatibility check

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#140]
Due to our recent problems with the new Xen versions I would like to ask to confirm whether the current bundle shipped with Sandbox 0.6.0 is working correctly on all our machines.

* [x] @BonusPlay DELL PowerEdge FX2
* [x] @chivay VMware Player hosted on Linux
* [x] @icedevml VMware Player hosted on Windows
* [x] @icedevml DELL PowerEdge R640

**Comment by chivay** [comment]
Running Debian 10 on VMware Player (Linux host)
```
$ sha256sum Win10_1909_English_x64.iso
01bf1eb643f7e50d0438f4f74fb91468d35cde2c82b07abc1390d47fc6a356be  Win10_1909_English_x64.iso
```

* System installs, reboots to desktop without any issues
* Postinstall works, offsets are extracted correctly
* DRAKVUF works, logs are generated
* However Windows shell seems to be unresponsive (with only cursor moving smoothly), sample is not run in reasonable time.
 
Overall, this issue seems to be related with Windows 10 and the sandbox works as intended.
No hard Xen lockups occurred.

**Comment by icedevml** [comment]
@chivay Thanks. Win10 sample not running in reasonable time seems to be separate issue and let's assume this test is passed in terms of Xen.

**Comment by icedevml** [comment]
VMware Player setup: Windows 10 (VMware Player host) -> Debian Buster (Xen Dom0) -> Windows 7 (DomU)
```
$ sha256sum SW_DVD5_Win_Pro_7w_SP1_64BIT_Polish_-2_MLF_X17-59386.ISO
1e94ef310fc6a4b202435b1309c6ee69b9807a0505d39dd553ea4cdb16d6ff6f  SW_DVD5_Win_Pro_7w_SP1_64BIT_Polish_-2_MLF_X17-59386.ISO
```
* Setup works properly
* Sample runs properly
* No Xen lockups/deadlocks observed
