### ISSUE TITLE
Load components async

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/drakvuf-sandbox#181]
Currently some components (analysis graph, tree) are loaded synchronously. This blocks entire website for long periods of time. We should do something like this https://medium.com/front-end-weekly/loading-components-asynchronously-in-react-app-with-an-hoc-61ca27c4fda7 to prevent it.

**Comment by psrok1** [comment]
I think that asynchronous components won't work because JavaScript is single-threaded and it will block even if calculations are done in async context.

I've done short debugging with profiler - it looks like Graphviz component spends a lot of time in `layoutDone` callback.

![image](https://user-images.githubusercontent.com/8720367/88405424-8adec100-cdcf-11ea-83e4-e254c6254c13.png)
![image](https://user-images.githubusercontent.com/8720367/88405431-8e724800-cdcf-11ea-91e2-d463507ac9ff.png)

Component `<Graphviz>` is rendered twice: first during `componentDidMount` and second time during `componentDidUpdate`

Evaluation of graph layout takes relatively short time, but post-processing after layout is pretty time-consuming. Especially during componentDidUpdate render.

![image](https://user-images.githubusercontent.com/8720367/88405781-06407280-cdd0-11ea-97fa-658f48564a3d.png)

I suggest avoid `<Graphviz>` component re-rendering: it should be rendered once just after gathering `process_tree` data. It seems that update of already rendered graph is much more difficult task for component than rendering it from scratch.

Notice that website blocks for a long time only when complete graph is already visible on webpage. Initial render usually takes 2-3 seconds and graph is not visible during that event.
