### ISSUE TITLE
Add support for users to write their own plugin

### ISSUE THREAD

**Issue by SigmaStar** [CERT-Polska/drakvuf-sandbox#670]
**Is your feature request related to a problem? Please describe.**

I am trying to log something at the point the malware is performing specific action. The only thing useful I found is "hooks.txt" under /etc/drakrun, But I can only log the action, which means I can't maintain a context information for latter analysis job. I think maybe drakvuf need a plugin system which makes it easy for users to write their own plugins in Python or C and hooks some api et. al. 

**Describe the solution you'd like**

Maybe we can learn something from Cuckoo Sandbox. They provide community signature system to detect specific type of high-risk action. But currently I don't have any idea how this plugin system could be built. I will update this issue as soon as possible if I get some new idea.

**Comment by manorit2001** [comment]
You can maybe try making plugins using the upstream DRAKVUF (https://github.com/tklengyel/drakvuf). It actually has a plugin support in c++ which lets you make plugins of your own as per your needs. It can help you give you raw outputs of the things that you want. 

You can try having a look at [DRAKVUF-Developers-Guide](https://github.com/tklengyel/drakvuf/wiki/DRAKVUF-Developers-Guide) as well as the existing plugins in [src/plugins](https://github.com/tklengyel/drakvuf/tree/master/src/plugins). I hope it might help you out

**Comment by SigmaStar** [comment]
But I wanna dynamically load or unload plugins,. And Is that possible if I want to write some plugins in python?

**Comment by manorit2001** [comment]
> But I wanna dynamically load or unload plugins, And Is that possible if I want to write some plugins in python?

I am not sure if it'll work that way, or at least **I** don't know how will that be accomplished. Maybe the authors could give you more insights on that. But from what I know, DRAKVUF Sandbox is just a wrapper around the underlying DRAKVUF engine which actually hooks into the VM to analyse the malware sample and give raw logs. DRAKVUF Sandbox then parses those outputs and dumps to extract information in a user friendly way and show it to the user. And the underlying DRAKVUF is a project purely based on C/C++ as it has to interact with the hypervisor using low level APIs so that it's presence is not visible to the malware making it stealthy for analysis

**Comment by SigmaStar** [comment]
Thanks! I got it.
