### ISSUE TITLE
External minio instance conflict due to installation of drakvuf-sandbox 

### ISSUE THREAD

**Issue by desecnd** [CERT-Polska/drakvuf-sandbox#671]
Hi! : ) 

I'd like to use external minio preinstalled on the system for drakvuf-sandbox, but from what I've observed, sandbox installs its own default version which automatically binds to port 9000 (drak-minio.service) resulting in conflict, and I can't really see an option to disable it. 

https://github.com/CERT-Polska/drakvuf-sandbox/blob/ad5d76260fb52d85ef2fc084d13f5f3e3a3a2079/drakcore/debian/rules#L16

Is there a possibility to disable the installation of drakvuf-sandbox minio by default?

**Comment by psrok1** [comment]
Due to similar issues on our side, in current master version (https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.19.0-alpha1), MinIO is no longer a built-in component and S3 storage needs to be installed separately.

Proper documentation for new setup is currently in progress, partially updated by https://github.com/CERT-Polska/drakvuf-sandbox/pull/915.
